version: "3.3"
services:
    reverseproxy:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - users-service
            - catalog-service
            - orders-service
    users-service:
        build: ./users-service
        ports:
            - 8001:8080
    catalog-service:
        build: ./catalog-service
        ports:
            - 8002:80
    orders-service:
        build: ./orders-service
        ports:
            - 8003:80        
    sql:
        image: postgres
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: compratec
    mongodb-primary:
        image: 'bitnami/mongodb:latest'
        environment:
        - MONGODB_REPLICA_SET_MODE=primary
        - MOONGODB_USERNAME=compratec
        - MONGODB_PASSWORD=compratec
        - MONGODB_ROOT_PASSWORD=compratec
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
        ports:
        - "27017:27017"
        volumes:
        - 'mongodb_master_data:/bitnami'

    mongodb-secondary:
        image: 'bitnami/mongodb:latest'
        depends_on:
        - mongodb-primary
        environment:
        - MONGODB_REPLICA_SET_MODE=secondary
        - MONGODB_PRIMARY_HOST=mongodb-primary
        - MOONGODB_USERNAME=compratec
        - MONGODB_PASSWORD=compratec
        - MONGODB_PRIMARY_PORT_NUMBER=27017
        - MONGODB_PRIMARY_ROOT_PASSWORD=compratec
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
        ports:
        - "27018:27017"

    mongodb-arbiter:
        image: 'bitnami/mongodb:latest'
        depends_on:
        - mongodb-primary
        environment:
        - MONGODB_REPLICA_SET_MODE=arbiter
        - MONGODB_PRIMARY_HOST=mongodb-primary
        - MONGODB_PRIMARY_PORT_NUMBER=27017
        - MOONGODB_USERNAME=compratec
        - MONGODB_PASSWORD=compratec|
        - MONGODB_PRIMARY_ROOT_PASSWORD=compratec
        - MONGODB_REPLICA_SET_KEY=replicasetkey123
  
volumes:
    db-data:
        driver: local
    mongodb_master_data:
        driver: local
