version: "3.3"
services:
    reverseproxy:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - users-service
            - catalog-service
            - orders-service
    users-service:
        build: ./users-service
        ports:
            - 8001:8080
    catalog-service:
        build: ./catalog-service
        volumes:
            - ./catalog-service:/usr/src/app
        ports:
            - 8002:80
    orders-service:
        build: ./orders-service
        ports:
            - 8003:80        
    sql:
        image: postgres
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: compratec
    
    mongodb-primary:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: compratec
        ports:
            - "27017:27017"
        volumes:
            - 'mongodb_master_data:/data/db'
  
volumes:
    db-data:
        driver: local
    mongodb_master_data:
        driver: local
