version: "3.3"
services:
    reverseproxy:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - users-service
            - catalog-service
            - orders-service
        deploy:
            placement:
                constraints:
                - node.role == manager
    users-service:
        build: ./users-service
        image: paroque28/compratec:users-service
    catalog-service:
        build: ./catalog-service
        volumes:
            - ./catalog-service:/usr/src/app
        image: paroque28/compratec:catalog-service
    orders-service:
        build: ./orders-service
        volumes:
                - ./orders-service:/home/node/app
        image: paroque28/compratec:orders-service 
    sql:
        image: postgres
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - sql-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: compratec
    
    mongodb-primary:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: compratec
        ports:
            - 27017:27017
        volumes:
            - 'mongodb_master_data:/data/db'
  
volumes:
    sql-data:
        driver: local
    mongodb_master_data:
        driver: local
